### ISSUE TITLE
Change text for delivery milestone's dialog's  content (button, title and description)

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2267]
Same text is shown for both website and VD project's delivery milestone's dialog's content (button, title and description)

![screen shot 2018-08-02 at 2 54 07 pm](https://user-images.githubusercontent.com/11248478/43575343-3eaf6112-9664-11e8-9791-8387121b9951.png)

**Comment by RishiRajSahu** [comment]
@vic-topcoder other than planned, active, completed text we are showing `dialogue boxes` for various actions pending on user for eg - `Design Acceptance` . We might need definition of such dialogue boxes for different kind of products as well.

**Comment by vic-topcoder** [comment]
Yes - that's a good capture - we'll have to ask @acshields and @rmjmccormick for content on those elements - their English is much better than mine. Let's capture those acceptance messages in the milestone document and list all the instances and content.

**Comment by rmjmccormick** [comment]
@vic-topcoder @acshields Adding the language for the dialogue boxes to the milestone document.

**Comment by gondzo** [comment]
@RishiRajSahu @vikasrohit 
Should we introduce a new milestone type `delivery-dev` and customize the message based on type? We don't need to add a new milestone component to do that.

**Comment by vikasrohit** [comment]
@gondzo I think that is better and logical approach.

@maxceem do you think you can get it done by tomorrow EOD?

**Comment by vikasrohit** [comment]
Also, I think we should now rename the `delivery` type to `delivery-design` to avoid confusion in future.

**Comment by maxceem** [comment]
@vikasrohit I'll try to do it now. Will create a new milestone and rename existent one myself if you didn't do it yet.

**Comment by vikasrohit** [comment]
Done in database level. Now it would break if you don't adapt the UI for delivery-dev milestone type. 😬

**Comment by maxceem** [comment]
Done with PR https://github.com/appirio-tech/connect-app/pull/2295

Also, renamed `delivery` type to `delivery-design` in the DB.

I've added a fallback for already existent milestones with `delivery` type so projects which are created for testing still works. After a while, we may remove the fallback and do not support `delivery` milestones.

**Comment by vikasrohit** [comment]
Thanks @maxceem I think in future, we need to keep these texts in details json (we need to add new field in milestone template model) so that we can keep them more dynamic and allow managers/admins to update.

**Comment by vikasrohit** [comment]
@rmjmccormick I think we are still missing the copy for the delivery milestone in the [doc](https://docs.google.com/spreadsheets/d/1SXZjX5TlbfFa7IuifOseCKqvqkytxeXUEH3A1rL0CCw/).

**Comment by rmjmccormick** [comment]
@vikasrohit Updates made (in red) into [https://docs.google.com/spreadsheets/d/1SXZjX5TlbfFa7IuifOseCKqvqkytxeXUEH3A1rL0CCw/edit]

**Comment by vikasrohit** [comment]
Thanks @rmjmccormick, @RishiRajSahu fyi
