### ISSUE TITLE
Hide blue line where milestone only has a description

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2293]
In case there is only description and nothing else in the milestone, the blue line has to be hidden.

![](https://user-images.githubusercontent.com/146016/43671910-9361f694-97d5-11e8-98f0-07f29d72998c.png)

**Comment by vikasrohit** [comment]
Good catch @maxceem

**Comment by maxceem** [comment]
Done.

It required us to move description to each of milestone type component which looks like repeating the same code. But I think very soon we will show description not only depend on the status but also depend on many other conditions specific to milestone type. So this change will be a good base for that.

**Comment by vikasrohit** [comment]
@maxceem I am still seeing the issue after merging the PR.

<img width="387" alt="screen shot 2018-08-09 at 2 18 22 pm" src="https://user-images.githubusercontent.com/2417632/43888366-2531d712-9bdf-11e8-9614-c2ce462a59b2.png">

**Comment by maxceem** [comment]
@vikasrohit could you please share with me which user do you use, and what project id it is?

**Comment by maxceem** [comment]
@vikasrohit could you please share with me which user do you use?

**Comment by maxceem** [comment]
Fixed

**Comment by vikasrohit** [comment]
Working fine now. Closing.
