### ISSUE TITLE
[Project Dashbord] No confirmation on project status change

### ISSUE THREAD

**Issue by arifnyet** [appirio-tech/connect-app#244]
### Expected behavior
Upon changing project status to complete and cancelled.. a confirmation is needed in to prevent human error

### Actual behavior
No confirmation on project status change(For completed and cancelled). Once it is clicked

### Steps to reproduce the problem
1.Open project dashboard
2.change the status to complete/cancelled

### Screenshot/screencast
Attach or link a resource.
![screenshot 12](https://cloud.githubusercontent.com/assets/8684209/18930828/32ef5834-85fc-11e6-85a5-1160529dc642.png)
![screenshot 11](https://cloud.githubusercontent.com/assets/8684209/18958659/efe949ce-8695-11e6-87b5-14b1f02b311e.png)

--

#### Environment
- OS: Windows 10
- Browser (w/version):Google Chrome Version 53.0.2785.116 m (64-bit)
- User role :Manager
- Account used: Pat Monahan

**Comment by parthshah** [comment]
@fnisen how do you want to handle this? Where do you want to show a confirmation dialog?

**Comment by fnisen** [comment]
@parthshah I'd like to follow the same style we use for project member removal: show the dialog in-line, below the status, with a message and confirmation buttons: 

![screen shot 2016-10-11 at 10 23 46 am](https://cloud.githubusercontent.com/assets/12552247/19280974/d07a18e2-8f9c-11e6-8835-d3676fde47a6.png)

Do you want this quickly mocked up?

**Comment by vikasrohit** [comment]
Further, should we show confirmation modal only when project status is changed to 'completed/cancelled' or it should be shown for every status change?

**Comment by fnisen** [comment]
@vikasrohit I was thinking only completed or canceled b/c those statuses may remove the project from the customer view (and eventually trigger some other actions down the line). The other statuses are more easily reversible.

**Comment by vikasrohit** [comment]
Changes are in dev.

**Comment by fnisen** [comment]
@vikasrohit this 
<img width="410" alt="screen shot 2016-10-14 at 10 00 41 am" src="https://cloud.githubusercontent.com/assets/12552247/19396046/c975fd3a-91f5-11e6-9db8-d0a925950a89.png"> 
is different in style from this 
<img width="423" alt="screen shot 2016-10-14 at 10 01 13 am" src="https://cloud.githubusercontent.com/assets/12552247/19396045/c97594e4-91f5-11e6-85d9-2a431cb7104d.png"> 
and neither completely matches Vic's design:  
![273e50e4-0a5a-411d-9df9-011e075005c3](https://cloud.githubusercontent.com/assets/12552247/19395992/8b509da8-91f5-11e6-811c-50a77bff1d69.png)
https://drive.google.com/drive/u/0/folders/0B1LbmKnex41fU18zSE9WMEVJNFU

Please make them both up to spec (e.g., the copy should be center-aligned).

**Comment by vikasrohit** [comment]
Done. All modal in the left panel, of the project specs page, are now in sync with the specs. Changes are in dev.

**Comment by fnisen** [comment]
@vikasrohit, sorry, still seeing a number of things not up to spec:

1. Deleting a link does not span the entire panel and doesn't have the correct button style on "Cancel": 
<img width="414" alt="screen shot 2016-10-25 at 12 22 55 pm" src="https://cloud.githubusercontent.com/assets/12552247/19700977/52530d3a-9aae-11e6-8f24-ceda79d07eb0.png">

2. Deleting a link does not "grey out" the entire section (I can still try to delete another link when the confirmation message is open): 
<img width="436" alt="screen shot 2016-10-25 at 12 25 34 pm" src="https://cloud.githubusercontent.com/assets/12552247/19701067/a80247a0-9aae-11e6-8cf6-9ad6370be037.png">

3. Project status change confirmation does not span the entire panel and also has the wrong button style on "Cancel": 
<img width="400" alt="screen shot 2016-10-25 at 12 24 49 pm" src="https://cloud.githubusercontent.com/assets/12552247/19701029/8668c22c-9aae-11e6-96b0-aa24dd097c11.png">
- Also, can you please change the button message to be more specific: "Close Project" and "Cancel Project"? 

For reference, team management is working/looking correctly: 
<img width="387" alt="screen shot 2016-10-24 at 4 43 30 pm" src="https://cloud.githubusercontent.com/assets/12552247/19701101/c8f7cb06-9aae-11e6-9f00-dd63c97fa472.png">

**Comment by fnisen** [comment]
There is already an open bug for #2 above: https://github.com/appirio-tech/connect-app/issues/353

**Comment by vikasrohit** [comment]
Fixed. Changes are in dev. Please let me know if you still see any issues.

**Comment by fnisen** [comment]
Works perfectly. Thanks @vikasrohit.
