### ISSUE TITLE
[$50] Sidebar jumps when we mark milestone as completed

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2511]
When we mark some milestone as completed and loading indicator is being shown, the sidebar jumps, see demo video https://monosnap.com/file/V09BUP4V3RHO3nHKwdnv5TEsNSCH8G

![image](https://user-images.githubusercontent.com/146016/45526215-db1a8e80-b808-11e8-848f-4d0c4596a86a.png)

It happens not always, probably when browser window has been scrolled and we change the last phase's milestone.

Possible related with https://github.com/appirio-tech/connect-app/issues/2149, but that one I couldn't reproduce.

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-479

**Comment by vikasrohit** [comment]
@maxceem I think we got this fixed in CF 11. Can you please check taking latest from dev?

**Comment by maxceem** [comment]
@vikasrohit I can still reproduce it for this project https://connect.topcoder-dev.com/projects/7301/plan if I complete milestone in the last phase.

Also, I've pulled the latest div locally and can reproduce the issue too, with the mentioned project.

**Comment by vikasrohit** [comment]
Ohk. Then this might be an edge case for #2422

**Comment by sumitdaga** [comment]
@maxceem 
please assign this to me!

**Comment by sumitdaga** [comment]
@maxceem 
please unassign me!
i would like to take a dig at other issues first

**Comment by Gauravseta** [comment]
@maxceem pls assign to me thnaks

**Comment by maxceem** [comment]
As the issue hasn't been completed during 12 hours and no comment was provided, this issue is now open for pick up.

**Comment by zjuasmn** [comment]
works on it

**Comment by zjuasmn** [comment]
done, please check #2621

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
