### ISSUE TITLE
Format of Italicized "G" in Projects App UI Bug

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4087]
Description: When font is italicized in Connect Projects app, the letter "g" looks odd. 

![weird_G_in_italics](https://user-images.githubusercontent.com/41118149/90034239-fbb62200-dc85-11ea-9aef-d74294490d83.PNG)

**Comment by maxceem** [comment]
As this issue might very browser/environment specific, is it possible to get more details about this issue:
1. Where such an italic text could be found? The exact place in the Connect App.
2. What is the browser name and version?
3. What is the operating system name and version?

**Comment by RishiRajSahu** [comment]
@acshields could you please provide the source of the issue ? i.e. who reported this ? or If you yourself encountered this could you please provide the info on above thread ?

**Comment by acshields** [comment]
Hi @RishiRajSahu - ketzjs09 reported this issue. Please follow up with him - I didn't get the browser version/OS from him.

**Comment by RishiRajSahu** [comment]
@acshields @maxceem I have also dropped a note to ketjs09 regarding same waiting for this reply.

**Comment by ketzjs09** [comment]
Using Windows 10, Chrome.

The weird g is visible when I try to write something in italics in Connect messages in our conversations with the client.

**Comment by maxceem** [comment]
Fixed via PR https://github.com/appirio-tech/connect-app/pull/4121

![image](https://user-images.githubusercontent.com/146016/92914968-c8a5b080-f434-11ea-8fa4-bf359e197237.png)

1. Generated new files in `woff` format, as old files had been generated a long time ago and the tool which has been used has some issues which cause the font rendering issues.

2. Additionally added files in `woff2` format. This is modern font format which reduces font size by 27% in comparison with `woff`. So all the browsers which support it (like Chrome) would use `woff2` now. This format also doesn't have issues with rendering.

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. Issue still exists.

![image](https://user-images.githubusercontent.com/55895538/94102949-42df2780-fe6e-11ea-881f-d908804108db.png)

OS: Windows 10
Chrome version: Version 85.0.4183.121

cc: @lakshmiathreya

**Comment by maxceem** [comment]
@sandhiyakavi please use `TEST01` environment https://connect-test01.topcoder-dev.com/ to test the current `Ready for QA` issues not `DEV` environment https://connect.topcoder-dev.com/.

**Comment by sandhiyakavi** [comment]
Verified.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/94116186-ab85ce80-fe85-11ea-9025-5e34a2645fa8.png)

cc: @lakshmiathreya

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/94555931-41ab6180-0297-11eb-9df9-6a4f4e923e8a.png)

cc: @lakshmiathreya
