### ISSUE TITLE
Connect Login/Logout redirect not working correctly in Safari

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#566]
Two issues:
1. From "connect.topcoder.com," hitting Login takes user to "https://accounts.topcoder.com/member," instead of "https://accounts.topcoder.com/connect?retUrl=https:%2F%2Fconnect.topcoder.com%2F"

2. Logging out from Connect takes a user to their member Dashboard, not to "connect.topcoder.com"

Only seeing these in Safari for some reason, not Chrome or Firefox.

**Comment by vikasrohit** [comment]
Fixed. Changes are in dev.

**Comment by fnisen** [comment]
@vikasrohit, part 2 of the issue is still not working: logging out from Connect takes a user to their member Dashboard, not to "connect.topcoder.com."

**Comment by vikasrohit** [comment]
My bad @fnisen Missed the second requirement completely. Fixed now.

**Comment by fnisen** [comment]
No problem. Working correctly now. 👍
